---

# Locale
- locale_gen: name=en_US.UTF-8 state=present

# Add Jenkins repository
- include: repo.yml

# Install dependencies
- include: dependencies_deb.yml

# Install Jenkins
- name: Install Jenkins
  sudo: yes
  apt: pkg=jenkins state=latest update_cache=yes cache_valid_time=86400